//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capybara.EditorPlugin.RegexMASPRovider_2017 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PluginResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capybara.EditorPlugin.RegexMASPRovider_2017.PluginResources", typeof(PluginResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Show regex evaluation list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EvaluationPopupWindowAction_Description {
            get {
                return ResourceManager.GetString("EvaluationPopupWindowAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Regex Evaluation List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EvaluationPopupWindowAction_Name {
            get {
                return ResourceManager.GetString("EvaluationPopupWindowAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AutoSuggest provider for copying the source words that match the specified regular expressions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex Match AutoSuggest Provider に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon RegexMASProvider_Icon {
            get {
                object obj = ResourceManager.GetObject("RegexMASProvider_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Show all regex-matched suggestions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuggestionsPopupWindowAction_Description {
            get {
                return ResourceManager.GetString("SuggestionsPopupWindowAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Regex Match Suggestions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuggestionsPopupWindowAction_Name {
            get {
                return ResourceManager.GetString("SuggestionsPopupWindowAction_Name", resourceCulture);
            }
        }
    }
}
